apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace:  kafka
  labels:
    app: kafka-app
spec:
  clusterIP: None
  ports:
    - name: "9092"
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace:  kafka
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      initContainers:
        - name: init-broker-id
          image: busybox
          command:
            - /bin/sh
            - -c
            - >
              echo ${echo $POD_NAME | awk -F '-' '{print $NF}') > /etc/broker-id/broker-id;
      containers:
        - name: kafka-container
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_BROKER_ID
              value:  spec.containers[0].name
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-svc:9092"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-svc:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
            - name: broker-id
              mountPath: /etc/broker-id
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
    - metadata:
        name: broker-id
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Mi"
